apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gog
  janus-idp.io/tekton: gog
  backstage.io/kubernetes-id: gog
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gog
resources:
- deployment.yaml
- route.yaml
- service.yaml
